version: '3.5'

services:

  dockerwall:
    build: .
    image: flaviostutz/dockerwall
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - LOG_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  test:
    image: busybox:1.29
    command: sh -c "ping www.google.com"
    labels:
      - "dockerwall.outbound=www.yahoo.com,www.google.com"

