version: '3.5'

services:

  dockerwall:
    build: .
    image: flaviostutz/dockerwall
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  test:
    image: busybox:1.29
    command: sh -c "ping 8.8.8.8"
    deploy:
      labels:
        - "dockerwall.outbound=www.google.com"
    labels:
      - "dockerwall.outbound=www.yahoo.com,www.uol.com.br"

